Refactor to use common nova code.  Allow upgrades essex -> folsom.

diff --git a/hooks/lib/openstack-common b/hooks/lib/openstack-common
--- a/hooks/lib/openstack-common
+++ b/hooks/lib/openstack-common
@@ -1,87 +1,48 @@
 #!/bin/bash -e
 
-# Common utility functions used across all nova charms.
-# Assumes $CHARM is set to charm name (for logging).
-
+# Common utility functions used across all OpenStack charms.
 
 error_out() {
   juju-log "$CHARM ERROR: $@"
   exit 1
 }
 
-function set_config_flags() {
-  # Set user-defined nova.conf flags from deployment config
-  juju-log "$CHARM: Processing config-flags."
-  flags=$(config-get config-flags)
-  if [[ "$flags" != "None" && -n "$flags" ]] ; then
-    for f in $(echo $flags | sed -e 's/,/ /g') ; do
-      k=$(echo $f | cut -d= -f1)
-      v=$(echo $f | cut -d= -f2)
-      set_or_update "$k" "$v"
-    done
-  fi
-}
-
-function nova_ctl_status {
+function service_ctl_status {
   # Return 0 if a service is running, 1 otherwise.
   local svc="$1"
   local status=$(service $svc status | cut -d/ -f1 | awk '{ print $2 }')
   case $status in
     "start") return 0 ;;
     "stop") return 1 ;;
-    *) echo "ERROR: Unexpected status of service $svc: $status" && exit 1 ;;
+    *) error_out "Unexpected status of service $svc: $status" ;;
   esac
 }
 
-function nova_ctl {
+function service_ctl {
   # control a specific service, or all (as defined by $SERVICES)
   if [[ $1 == "all" ]] ; then
     ctl="$SERVICES"
   else
     ctl="$1"
   fi
-  action=$2
-  if [[ -z $ctl ]] || [[ -z $action ]] ; then
-    juju-log "ERROR nova_ctl: Not enough arguments"
-    exit 1
+  action="$2"
+  if [[ -z "$ctl" ]] || [[ -z "$action" ]] ; then
+    error_out "ERROR service_ctl: Not enough arguments"
   fi
+
   for i in $ctl ; do
     case $action in
       "start")
-        nova_ctl_status $i || service $i start ;;
+        service_ctl_status $i || service $i start ;;
       "stop")
-        nova_ctl_status $i && service $i stop || return 0 ;;
+        service_ctl_status $i && service $i stop || return 0 ;;
       "restart")
-        nova_ctl_status $i && service $i restart || service $i start ;;
+        service_ctl_status $i && service $i restart || service $i start ;;
     esac
     if [[ $? != 0 ]] ; then
-      juju-log "$CHARM: nova_ctl ERROR - Service $i failed to $action"
+      juju-log "$CHARM: service_ctl ERROR - Service $i failed to $action"
     fi
   done
-}
-
-configure_volume_service() {
-  local svc="$1"
-  case "$svc" in
-    "cinder") set_or_update "volume_api_class" "nova.volume.cinder.API" ;;
-    "nova-volume") set_or_update "volume_api_class" "nova.volume.api.API" ;;
-    *) juju-log "$CHARM ERROR - configure_volume_service: Invalid service $svc"
-       return 1 ;;
-  esac
-}
-
-function configure_network_manager {
-  local manager="$1"
-  echo "$CHARM: configuring $manager network manager"
-  case $1 in
-    "FlatManager")
-      set_or_update "network_manager" "nova.network.manager.FlatManager"
-      ;;
-    "FlatDHCPManager")
-      set_or_update "network_manager" "nova.network.manager.FlatDHCPManager"
-      ;;
-    *) echo "ERROR: Invalid network manager $1" && exit 1 ;;
-  esac
 }
 
 function configure_install_source {
@@ -197,45 +158,4 @@ get_os_version_codename() {
     "folsom") echo "2012.2" ;;
     "grizzly") echo "2012.3" ;;
   esac
-}
-
-
-set_or_update() {
-  # Update config flags in nova.conf or api-paste.ini.
-  # Config layout changed in Folsom, so this is now OpenStack release specific.
-  local rel=$(get_os_codename_package "nova-common")
-  . $CHARM_DIR/lib/$rel
-  nova_set_or_update $@
-}
-
-do_openstack_upgrade() {
-  # update openstack components to those provided by a new installation source
-  # it is assumed the calling hook has confirmed that the upgrade is sane.
-  local rel="$1"
-  shift
-  local packages=$@
-
-  orig_os_rel=$(get_os_codename_package "nova-common")
-  new_rel=$(get_os_codename_install_source "$rel")
-
-  # Backup the config directory.
-  local stamp=$(date +"%Y%m%d%M%S")
-  tar -pcf /var/lib/juju/$CHARM-backup-$stamp.tar $CONF_DIR
-
-  # load the release helper library for pre/post upgrade hooks specific to the
-  # release we are upgrading to.
-  . $CHARM_DIR/lib/$new_rel
-
-  # new release specific pre-upgrade hook
-  nova_pre_upgrade "$orig_os_rel"
-
-  # Setup apt repository access and kick off the actual package upgrade.
-  configure_install_source "$rel"
-  apt-get update
-  DEBIAN_FRONTEND=noninteractive apt-get --option Dpkg::Options::=--force-confold -y \
-     install --no-install-recommends $packages
-
-  # new release sepcific post-upgrade hook
-  nova_post_upgrade "$orig_os_rel"
-
 }
