Sync openstack-common.

diff --git a/hooks/lib/openstack-common b/hooks/lib/openstack-common
--- a/hooks/lib/openstack-common
+++ b/hooks/lib/openstack-common
@@ -167,7 +167,7 @@ get_os_codename_install_source() {
   # have a guess based on the deb string provided
   if [[ "${rel:0:3}" == "deb" ]] || \
      [[ "${rel:0:3}" == "ppa" ]] ; then
-    CODENAMES="diablo essex folsom grizzly havan"
+    CODENAMES="diablo essex folsom grizzly havana"
     for cname in $CODENAMES; do
       if echo $rel | grep -q $cname; then
         codename=$cname
@@ -324,7 +324,7 @@ HAPROXY_DEFAULT=/etc/default/haproxy
 
 ##########################################################################
 # Description: Configures HAProxy services for Openstack API's
-# Parameters: 
+# Parameters:
 #   Space delimited list of service:port combinations for which
 #   haproxy service configuration should be generated for.  The function
 #   assumes the name of the peer relation is 'cluster' and that every
@@ -332,7 +332,7 @@ HAPROXY_DEFAULT=/etc/default/haproxy
 #
 #   The HAProxy service will listen on port + 10000.
 # Example:
-#   configure_haproxy cinder_api:12345 nova_api:9999 
+#   configure_haproxy cinder_api:12345 nova_api:9999
 ##########################################################################
 configure_haproxy() {
   local address=`unit-get private-address`
@@ -524,4 +524,40 @@ except:
 if value.startswith('%'): exit(0)
 print value
 "
+}
+
+##########################################################################
+# Description: Creates an rc file exporting environment variables to a
+# script_path local to the charm's installed directory.
+# Any charm scripts run outside the juju hook environment can source this
+# scriptrc to obtain updated config information necessary to perform health
+# checks or service changes
+#
+# Parameters:
+#   An array of '=' delimited  ENV_VAR:value combinations to export.
+#   If optional script_path key is not provided in the array, script_path
+#     defaults to scripts/scriptrc
+##########################################################################
+function save_script_rc {
+  if [ ! -n "$JUJU_UNIT_NAME" ]; then
+     echo "Error: Missing JUJU_UNIT_NAME environment variable"
+     exit 1
+  fi
+  # our default unit_path
+  unit_path="/var/lib/juju/units/${JUJU_UNIT_NAME/\//-}/charm/scripts/scriptrc"
+  echo $unit_path
+  tmp_rc="/tmp/${JUJU_UNIT_NAME/\//-}rc"
+
+  echo "#!/bin/bash" > $tmp_rc
+  for env_var in "${@}"
+  do
+    if `echo $env_var | grep -q script_path`; then
+       # well then we need to reset the new unit-local script path
+       unit_path="/var/lib/juju/units/${JUJU_UNIT_NAME/\//-}/charm/${env_var/script_path=/}"
+    else
+       echo "export $env_var" >> $tmp_rc
+    fi
+  done
+  chmod 755 $tmp_rc
+  mv $tmp_rc $unit_path
 }
