Reworked get_ip to be 12.04 compatible, check return is valid before use

diff --git a/hooks/nova-compute-common b/hooks/nova-compute-common
--- a/hooks/nova-compute-common
+++ b/hooks/nova-compute-common
@@ -88,6 +88,10 @@ function configure_network_manager {
   local quantum_plugin=$2
   local network_bridge=$(config-get bridge-interface)
   local private_address=$(get_ip `unit-get private-address`)
+  # Check to ensure we can actually resolve
+  # the local unit IP address
+  [[ -n $private_address ]] || juju-log "Unable to resolve local IP address" \
+    && exit 1
 
   # Store the network manager and quantum plugin
   # for use in later hook invocations
