Use CHARM_DIR

diff --git a/hooks/lib/nova/nova-common b/hooks/lib/nova/nova-common
--- a/hooks/lib/nova/nova-common
+++ b/hooks/lib/nova/nova-common
@@ -3,19 +3,20 @@
 # Common utility functions used across all nova charms.
 
 CONFIG_CHANGED=False
+HOOKS_DIR="$CHARM_DIR/hooks"
 
 # Load the common OpenStack helper library.
-if [[ -e $CHARM_DIR/lib/openstack-common ]] ; then
-  . $CHARM_DIR/lib/openstack-common
+if [[ -e $HOOKS_DIR/lib/openstack-common ]] ; then
+  . $HOOKS_DIR/lib/openstack-common
 else
-  juju-log "Couldn't load $CHARM_DIR/lib/opentack-common." && exit 1
+  juju-log "Couldn't load $HOOKS_DIR/lib/opentack-common." && exit 1
 fi
 
 set_or_update() {
   # Update config flags in nova.conf or api-paste.ini.
   # Config layout changed in Folsom, so this is now OpenStack release specific.
   local rel=$(get_os_codename_package "nova-common")
-  . $CHARM_DIR/lib/nova/$rel
+  . $HOOKS_DIR/lib/nova/$rel
   nova_set_or_update $@
 }
 
@@ -130,7 +131,7 @@ do_openstack_upgrade() {
 
   # load the release helper library for pre/post upgrade hooks specific to the
   # release we are upgrading to.
-  . $CHARM_DIR/lib/nova/$new_rel
+  . $HOOKS_DIR/lib/nova/$new_rel
 
   # new release specific pre-upgrade hook
   nova_pre_upgrade "$orig_os_rel"
